---
title: "Laporan Hasil Survei Kepuasan Pegawai Terhadap Layanan Sistem Payroll "
author: "Easbi Ikhsan"
date: "December 3, 2018"
output: html_document
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(data.table)

library(dplyr)

library(formattable)

library(tidyr)
library(data.table)
library(dplyr)
library(formattable)
library(scales)
library(tidyr)
library(DT)
library(ggplot2)
library(readxl)
library(shiny)
library(leaflet)
survei<- read_excel("C:/Users/bps/Downloads/Hasil Survei LAYANAN KEPUASAN ATM.xlsx", 
    col_types = c("numeric", "text", "numeric", 
        "text", "text", "text", "text", "text", 
        "text", "text", "text", "numeric", 
        "text", "text", "text", "text", "text", 
        "text", "text", "text", "text", "text", 
        "text", "text", "text", "text", "text", 
        "text", "text", "text", "text", "text", 
        "text", "text", "text", "text", "text", 
        "text", "text", "text", "text", "text", 
        "text", "text", "text", "text", "text", 
        "text", "text", "text", "text", "text", 
        "text", "text", "text", "text", "text", 
        "text", "text", "text", "numeric", 
        "numeric", "numeric", "numeric", 
        "numeric", "numeric", "numeric", 
        "numeric", "numeric", "numeric", 
        "numeric", "numeric", "numeric", 
        "numeric", "numeric", "numeric", 
        "numeric", "numeric", "numeric", 
        "numeric", "numeric", "numeric", 
        "numeric", "numeric", "numeric", 
        "numeric", "numeric", "numeric", 
        "numeric", "numeric", "numeric", 
        "numeric", "numeric", "numeric", 
        "numeric", "numeric", "numeric", 
        "numeric", "numeric", "numeric", 
        "numeric", "numeric"))

prep_text <- function(text){
  docs <- Corpus(VectorSource(text))
  toSpace <- content_transformer(function (x , pattern ) gsub(pattern, " ", x))
  docs <- tm_map(docs, toSpace, "/")
  docs <- tm_map(docs, toSpace, "@")
  docs <- tm_map(docs, toSpace, "\\|")
  # Convert the text to lower case
  docs <- tm_map(docs, content_transformer(tolower))
  # Remove numbers
  docs <- tm_map(docs, removeNumbers)
  # Remove english common stopwords
  docs <- tm_map(docs, removeWords, stopwords("english"))
  # Remove your own stop word
  # specify your stopwords as a character vector
  docs <- tm_map(docs, removeWords, c("blabla1", "blabla2")) 
  # Remove punctuations
  docs <- tm_map(docs, removePunctuation)
  # Eliminate extra white spaces
  docs <- tm_map(docs, stripWhitespace)
  # Text stemming
  docs <- tm_map(docs, stemDocument)
  dtm <- TermDocumentMatrix(docs)
  m <- as.matrix(dtm)
  v <- sort(rowSums(m),decreasing=TRUE)
  d <- data.frame(word = names(v),freq=v)
  return(d)
}

```

```{r, echo=FALSE}
library(leaflet)
m <- leaflet() %>%
  addTiles() %>%  # Add default OpenStreetMap map tiles
  addMarkers(lng=106.837328, lat=-6.165231, popup="Badan Pusat Statistik")
m
```

Survei Kepuasan Pegawai Terhadap Layanan Sistem Payroll di BPS diisi secara lengkap (complete) oleh `r nrow(survei)` dari 1400an pegawai BPS
```{r, echo=FALSE}
test1 <- as.data.frame(table(survei$a2))
ggplot(test1, aes(Var1, Freq)) + geom_bar(stat = "identity", fill = "#00B2B2") + geom_text(aes(label =
                                                                                                 Freq),
                                                                                           vjust = 1.6,
                                                                                           color = "white",
                                                                                           size = 3.5) +
  theme_minimal() + labs(x = "Jenis Kelamin", y = "Jumlah")


# Tabel 1. Jumlah pegawai menurut jenis bank yang digunakan sebagai payroll BPS

test2 <- as.data.frame(table(survei$a5))
ggplot(test2, aes(Var1, Freq)) + geom_bar(stat = "identity", fill = "#00B2B2") + geom_text(aes(label =
                                                                                                 Freq),
                                                                                           vjust = 1.6,
                                                                                           color = "white",
                                                                                           size = 3.5) +
  theme_minimal() + labs(x = "Bank", y = "Jumlah")

# Tabel 1.5 Jumlah pegawai menurut jenis bank dan jenis kelamin yang digunakan sebagai payroll BPS
test3 = data.frame(survei$a2, survei$a5)
test3 = table(test3)
test3 = as.data.frame(test3)

ggplot(test3, aes(x = survei.a5, y=Freq, fill=survei.a2)) + 
  geom_bar(stat="identity", position=position_dodge())+
  geom_text(aes(label=Freq), vjust=1.6, color="white",
            position = position_dodge(0.9), size=3.5)+
  labs(x = "Bank", y = "Jumlah", fill="Jenis Kelamin") +
  scale_fill_brewer(palette="Paired")+
  theme_minimal()
```

```{r survei, echo=FALSE}
#Set a few color variables to make our table more visually appealing
customGreen0 = "#E5FFFF"
customGreen = "#00B2B2"
customRed = "#ff7f7f"

tabel1 = data.frame(table(survei$h2))
colnames(tabel1) <- c("Bank", "Jumlah")
add_1 <- data.frame("Bank" = "BTN SYARIAH", "Jumlah" = 0)
tabel1 = rbind(tabel1, add_1)
tabel1$Persentase <- percent(tabel1$Jumlah / sum(tabel1$Jumlah))
as.datatable(formattable(tabel1,
                         align = c("l", "c", "c"),
                         list(
                           `Persentase` = color_tile(customGreen0, customGreen))
                         ))

```

## WordCloud

Berikut ini workcloud untuk masing2 permasalahan layanan:
```{r echo=FALSE}
library(shiny)
library(tm)
library(SnowballC)
library(RColorBrewer)
library(wordcloud)
library(readxl)
library(ggplot2)

survei<- read_excel("~/Book2.xlsx")
nms <- names(survei)

ui <- fluidPage(
  headerPanel("Wordcloud Permasalahan Bank BRI/BRI SYARIAH"),
  sidebarLayout(
    sidebarPanel(
      selectInput('x', 'X', choices = nms)
    ),
    
    # Show a plot of the generated distribution
    mainPanel(
      plotOutput("plot"),
      plotOutput("plot1")
    )
  )
)


server <- function(input, output) {
  output$plot <- renderPlot({
    tweetsDS <- survei[input$x]
    tweetsDS.Corpus<-Corpus(VectorSource(tweetsDS))
    
    ##Data Cleaning and Wrangling
    tweetsDS.Clean<-tm_map(tweetsDS.Corpus, PlainTextDocument)
    tweetsDS.Clean<-tm_map(tweetsDS.Corpus,tolower)
    tweetsDS.Clean<-tm_map(tweetsDS.Clean,removeNumbers)
    tweetsDS.Clean<-tm_map(tweetsDS.Clean,removeWords,stopwords("english"))
    tweetsDS.Clean<-tm_map(tweetsDS.Clean,removePunctuation)
    tweetsDS.Clean<-tm_map(tweetsDS.Clean,stripWhitespace)
    tweetsDS.Clean<-tm_map(tweetsDS.Clean,stemDocument)
    wordcloud(words = tweetsDS.Clean, min.freq = 1,
              max.words=100, random.order=FALSE, rot.per=0.35, 
              colors=brewer.pal(8, "Dark2"))

  })
  
  output$plot1 <- renderPlot({
    tweetsDS <- survei[input$x]
    tweetsDS.Corpus<-Corpus(VectorSource(tweetsDS))
    
    ##Data Cleaning and Wrangling
    tweetsDS.Clean<-tm_map(tweetsDS.Corpus, PlainTextDocument)
    tweetsDS.Clean<-tm_map(tweetsDS.Corpus,tolower)
    tweetsDS.Clean<-tm_map(tweetsDS.Clean,removeNumbers)
    tweetsDS.Clean<-tm_map(tweetsDS.Clean,removeWords,stopwords("english"))
    tweetsDS.Clean<-tm_map(tweetsDS.Clean,removePunctuation)
    tweetsDS.Clean<-tm_map(tweetsDS.Clean,stripWhitespace)
    tweetsDS.Clean<-tm_map(tweetsDS.Clean,stemDocument)
    dtm <- TermDocumentMatrix(tweetsDS.Clean)
    m <- as.matrix(dtm)
    v <- sort(rowSums(m),decreasing=TRUE)
    d <- data.frame(word = names(v),freq=v)
    the_data <- head(d, 10)
    ggplot(the_data, aes(x=reorder(word, -freq, sum), y=freq, fill="#00B2B2")) + geom_bar(stat="identity") +labs(x = "Kata", y = "Frekuensi", fill="Warna") +
      geom_text(aes(label = freq),  vjust = 1.6,color = "white",  size = 3.5)
  })
}
shinyApp(ui = ui, server = server)


```




